language: node_js
node_js:
  - "7"
branches:
  only:
  - master
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_44ad502b10c9_key -iv $encrypted_44ad502b10c9_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa 
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name '0x5e'
- git config --global user.email '0x5e@sina.cn'
install:
- yarn global add hexo-cli
- yarn
script:
- yarn run deploy  # hexo clean && hexo g -d
addons:
  ssh_known_hosts:
  - git.coding.net
