menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/0x5e
    Link: /links/
    Rss: /atom.xml

favicon: /favicon.ico
logo: /imgs/avatar.jpg

# Comment
# e.g disqus: seansun
disqus: '0x5e'
duoshuo:
cloudTie:

# Analytics
# google-analytics:
ga: UA-102733496-1

# Copyright Infomation
startyear: 2016
